Repository kyma-project/kim-snatch, pull requests merged in 2025-01, with the labels that each got.

#6 GitHub Actions, build-job for Snatch
  .github/workflows/build_snatch.yml
  CODEOWNERS
Labels: lgtm, cla: yes, size/M

#7 Change the Docker `workspace` to repair build job
  Dockerfile
Labels: lgtm, cla: yes, size/XS

#9 Add security scanners configuration
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#12 Configure scanners to follow latest snatch image
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#11 Add new set of GitHub Actions
  .github/dependabot.yml
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/vuln-check.yaml
Labels: lgtm, cla: yes, size/M

#15 Fix the Reuse issues
  .reuse/dep5
  README.md
  REUSE.toml
Labels: lgtm, cla: yes, size/M

#14 Adjust GitHub Actions after repository renaming
  .github/workflows/build_snatch.yml
  .github/workflows/daily-markdown-link-check.yaml
  .github/workflows/tests.yml
Labels: lgtm, cla: yes, size/S

#16 Update module name in sec-config
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#23 Adjust image name
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#13 Add fallback for misconfigured worker pool name case
  Makefile
  PROJECT
  cmd/main.go
  config/certmanager/issuer.yaml
  config/default/kustomization.yaml
  config/default/manager_webhook_patch.yaml
  config/default/metrics_service.yaml
  config/gardener/certmanager/certificate.yaml
  config/gardener/certmanager/issuer.yaml
  config/k3d/kustomization.yaml
  config/k3d/manager_webhook_patch.yaml
  config/k3d/metrics_service.yaml
  config/manager/kustomization.yaml
  config/manager/manager.yaml
  config/network-policy/allow-metrics-traffic.yaml
  config/network-policy/allow-webhook-traffic.yaml
  config/prometheus/monitor.yaml
  config/rbac/leader_election_role.yaml
  config/rbac/leader_election_role_binding.yaml
  config/rbac/role.yaml
  config/rbac/role_binding.yaml
  config/rbac/service_account.yaml
  config/webhook/kustomization.yaml
  config/webhook/manifests.yaml
  config/webhook/service.yaml
  go.mod
  internal/webhook/callback/callback_test.go
  internal/webhook/server/server.go
  internal/webhook/v1/pod_webhook.go
  internal/webhook/v1/webhook_suite_test.go
  test/e2e/e2e_suite_test.go
  test/e2e/e2e_test.go
Labels: lgtm, cla: yes, size/L

#27 Update scanners configuration
  Makefile
  config/manager/kustomization.yaml
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#28 Switch node selectors to node affinity
  cmd/main.go
  internal/webhook/v1/pod_webhook.go
  internal/webhook/v1/webhook_suite_test.go
  test/e2e/e2e_test.go
Labels: lgtm, cla: yes, size/M

#30 Update sec-scanners-config.yaml
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#31 Upgrade outdated libs + fix code smells
  go.mod
  go.sum
  internal/webhook/server/server.go
  test/utils/utils.go
Labels: lgtm, cla: yes, size/L

#32 Bump image for security scanners.
  config/manager/kustomization.yaml
  go.mod
  go.sum
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/M

#33 Remove race condition in go-routine
  internal/webhook/server/server.go
Labels: lgtm, cla: yes, size/M

#35 fix race condition
  internal/webhook/server/server.go
Labels: lgtm, cla: yes, size/XS

#36 Refactor webhook server
  internal/webhook/server/server.go
Labels: lgtm, cla: yes, size/S

#37 Bump security scanners configuration for release 0.0.5
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#38 Snatch docs
  docs/user/README.md
  docs/user/assets/snatch-deployment.svg
Labels: lgtm, cla: yes, size/M

#44 Bump security scanners configuration for release 0.0.6
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS
