Repository kyma-project/kim-snatch, pull requests merged in 2025-02, with the labels that each got.

#45 Create Prometheus metrics for `kim-snatch`
  cmd/main.go
  config/default/manager_metrics_patch.yaml
  config/default/metrics_service.yaml
  config/k3d/kustomization.yaml
  config/k3d/manager_metrics_patch.yaml
  config/k3d/metrics_service.yaml
  config/prometheus/monitor.yaml
  go.mod
  go.sum
  internal/metrics/metrics.go
  internal/metrics/mocks/Metrics.go
  internal/webhook/server/server.go
Labels: lgtm, cla: yes, size/L

#46 Update security configs to the latest release
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#47 Delete Kustomize patch for metrics endpoint
  config/default/kustomization.yaml
  config/k3d/kustomization.yaml
Labels: lgtm, cla: yes, size/XS

#49 Bump security scanners configuration for release 1.0.0
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/XS

#50 Fix controller e2e tests
  .github/workflows/tests.yml
  config/certmanager/certificate.yaml
  config/default/manager_webhook_patch.yaml
  config/gardener/certmanager/certificate.yaml
  config/k3d/kustomization.yaml
  config/k3d/manager_webhook_patch.yaml
  sec-scanners-config.yaml
  test/e2e/e2e_test.go
Labels: lgtm, cla: yes, size/L

#51 Bump security scanners configuration for release 1.0.0
  .github/workflows/tests.yml
  .github/workflows/vuln-check.yaml
  config/manager/kustomization.yaml
  go.mod
  sec-scanners-config.yaml
Labels: lgtm, cla: yes, size/S

#43 Technical docs for Snatch developers
  docs/contributor/README.md
  docs/contributor/assets/architecture-webhook.svg
  docs/contributor/assets/flow-snatch.svg
Labels: lgtm, cla: yes, size/M
